[[redirects]]
from = "/.well-known/assetlinks.json"
to = "/assetlinks.json"
status = 200
force = true # COMMENT: ensure that we always redirect
from = "/.well-known/apple-app-site-association"
to = "/apple-app-site-association.json"
status = 200
force = true # COMMENT: ensure that we always redirect
